version: "3"
services:
  app:
    image: node:latest
    working_dir: /app/ecommerce
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/app/ecommerce
  mongodb:
    image: mongo:4.4.24
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db